apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api-deployment
  labels:
    app: mlops-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: mlops-api-container
          image: moizsajjad/mlops-flask-api:latest
          ports:
            - containerPort: 5000
