apiVersion: v1
kind: Service
metadata:
  name: streamlit-frontend-service
spec:
  type: NodePort
  selector:
    app: streamlit-frontend
  ports:
    - port: 80
      targetPort: 8501
      nodePort: 30006
